language: php
php:
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'

env:
  - SYMFONY_VERSION="2.3.*"
  - SYMFONY_VERSION="2.7.*"
  - SYMFONY_VERSION="3.0.*"

before_script:
    - composer self-update
    - composer install
